version: '2'
services:
  app:
    build: .
    volumes:
      - .:/docker
    ports:
      - 8080:3000
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=mysql2://root:password@mysql/devdb
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode="" # disable strict mode
    volumes:
    - /var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=password
